[tool.poetry]
name = "heckorator"
version = "0.1.0"
description = "the most readable decorators you've ever seen"
authors = ["RocketRace <oliviaspalmu@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
